### ISSUE TITLE
Reading post data example

### ISSUE THREAD

**Issue by Mikulas** [reactphp/reactphp#137]
Hi,
could you please add an example of how post data would be read from request?
I tried reading the request as stream, but the result was empty so I suppose it's not the correct approach.

Request:
`curl --data "key=value" http://127.0.0.1:1337`

Thank you

**Comment by ingus** [comment]
To anybody who will get here pulling out hair because of memory leaks on post data reading with the example code above, be sure to call not only `$response -> end()`, but `$request -> close();` as well.

**Comment by generak13** [comment]
Hi. Is 'end' event implemented correctly? It doesn't work for me.
Code posted by zba is a the only approach to receive full POST data?

**Comment by WyriHaximus** [comment]
FYI the components have their on repository where development happens. In regards to POST data: https://github.com/reactphp/http/pull/41#issuecomment-252432624

**Comment by generak13** [comment]
I just have noticed that the second chunk of POST data in event onData triggers in 1 second. If there are three or more chunks issue is still reproduced only for second chunk, for others guys all works fine. Any ideas?

**Comment by generak13** [comment]
The problem was that I used cURL php library for sending request to server written on reactphp. As far as I can see, when I send long POST data cURL sets **Expect: 100-continue** header.
So it doesn't send POST body at this moment. That is why first chunk of the data on my server is empty. The example posted by _zba_ does not handle this header.

I think that cURL has something like timeout. So it does not receive any response from the server and sends request again with the actual data.

In order to fix this problem you should remove the header **Expect** from the client request:
`curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));`

or handle it on your server. I modified _zba_ code example with something like this:
```
$app = function ($request, $response) {
       $requestBody='';
        $headers=$request->getHeaders();
        $contentLength=(int)$headers['Content-Length'];
        $receivedData=0;
        if($request->expectsContinue()) {
            $response->writeContinue();
            $request->close(); //Need I close request connection?
        }
        $request->on('data',function($data) 
            use ($request, $response,&$requestBody,&$receivedData,$contentLength) {
                $requestBody.=$data;
                $receivedData+=strlen($data);
                if ($receivedData>=$contentLength) {
                        parse_str($requestBody, $requestData);
                        print_r($requestData); //here is our data
                        $response->end();
                }
        });
    }
```

**Comment by clue** [comment]
@generak13 this is expected behavior as per the RFC, see also https://github.com/reactphp/http/pull/47#issuecomment-238533224
