### ISSUE TITLE
Outdated blog posts

### ISSUE THREAD

**Issue by mmoreram** [reactphp/reactphp#431]
We should make some revisions about the blog posts and the talks in the main repository README file. For example, the "Super Speed Symfony - ReactPHP" is more than 3 years old, and is based on top of old versions for both Symfony and ReactPHP libraries.

**Comment by WyriHaximus** [comment]
Will go over them, some are even dead links now

**Comment by DavidGarciaCat** [comment]
Hello. I'm trying to test ReactPHP on a Symfony project, and I am having some troubles due to the non-updated content. Is this issue still relevant or is just that I couldn't find an updated post? Most of the content I found is for versions 0.x of ReactPHP, that implies it doesn't match/work with the current versions. Cheers,

**Comment by mmoreram** [comment]
Hello @DavidGarciaCat, if you want to check an example of how to work with Symfony using ReactPHP, I recommend you this demo - https://github.com/driftphp/demo/

Please, ask me whatever you need about this example :)

**Comment by Favy-source** [comment]
I want to assist and contribute in whichever way I can. 
Please assign some tasks to me

**Comment by WyriHaximus** [comment]
There is a redesign of the site coming that will deal with this in a better way
